name: "Install thrift"
description: "Installs thrift binary"
inputs:
  thrift-version:
    description: 'Thrift version to install'
    default: '0.14.2'
    required: false

runs:
  using: composite
  steps:
    - name: Download thrift
      run: |
        wget -O ./thrift.tar.gz "https://github.com/valitydev/thrift/releases/download/${{ inputs.thrift-version }}/thrift-${{ inputs.thrift-version }}-linux-x86_64.tar.gz"
      shell: bash
    - name: Unpack thrift
      run: |
        sudo tar -xvzf ./thrift.tar.gz -C /usr/bin/
      shell: bash
    - name: Check installation
      run: |
        thrift --version
      shell: bash
